Repository IntelLabs/matsciml, pull requests merged in 2023-10, with the labels that each got.

#55 Pre-commit workflow
  .pre-commit-config.yaml
  README.md
Labels: enhancement, dependencies

#54 Adding contribution file
  CONTRIBUTING.md
  CONTRIBUTORS.md
Labels: documentation

#60 Pre-commit fix and adding `isort`
  .pre-commit-config.yaml
Labels: bug

#59 Fix dependencies in `pyproject.toml` and provide conda spec
  README.md
  conda.yml
  pyproject.toml
Labels: bug, documentation

#61 PyG implementation of E(n)-GNN
  examples/model_demos/egnn_pyg.py
  matsciml/datasets/transforms/__init__.py
  matsciml/datasets/transforms/representations/graphs.py
  matsciml/models/base.py
  matsciml/models/pyg/__init__.py
  matsciml/models/pyg/egnn.py
  pyproject.toml
Labels: enhancement
