Repository IntelLabs/matsciml, pull requests merged in 2024-03, with the labels that each got.

#134 Adding FA Transform Back In
  matsciml/datasets/transforms/__init__.py
  matsciml/datasets/transforms/frame_averaging.py
Labels: bug, data

#135 Update MaterialsProjectDataset for mp-traj and gnome compatibility
  matsciml/datasets/materials_project/dataset.py
Labels: data, needs triage

#143 DGL dependency fix
  README.md
  conda.yml
Labels: bug, dependencies

#145 Tests refactor
  CONTRIBUTING.md
  matsciml/datasets/materials_project/tests/test_materials_project.py
  matsciml/datasets/nomad/tests/test_nomad.py
  matsciml/datasets/oqmd/tests/test_oqmd.py
  matsciml/datasets/tests/test_collate_function.py
  matsciml/datasets/tests/test_multi_dataset.py
  matsciml/datasets/tests/test_save_lmdb.py
  matsciml/lightning/__init__.py
  matsciml/lightning/data_utils.py
  matsciml/lightning/ddp.py
  matsciml/lightning/tests/test_cpu_ddp.py
  matsciml/models/dgl/__init__.py
  matsciml/models/dgl/dpp/tests/__init__.py
  matsciml/models/dgl/dpp/tests/test_dpp_dgl.py
  matsciml/models/dgl/tests/test_dgl_models.py
Labels: code maintenance

#144 Adding `pre-commit` workflow to Github actions
  .github/workflows/pre-commit-action.yml
Labels: code maintenance

#147 Fix for unused atomic embedding table in M3Gnet
  matsciml/models/dgl/m3gnet.py
  pyproject.toml
Labels: bug

#132 Add alexandria dataset to matsciml toolkit https://github.com/IntelLabs/matsciml/discussions/107
  MANIFEST.in
  examples/datasets/alexandria/download_alexandria.py
  examples/datasets/alexandria/single_task_base.py
  examples/datasets/alexandria/single_task_devset.py
  examples/datasets/alexandria/single_task_egnn.py
  examples/datasets/alexandria/single_task_gala.py
  examples/datasets/alexandria/single_task_mpnn_dgl.py
  matsciml/datasets/__init__.py
  matsciml/datasets/alexandria/README.md
  matsciml/datasets/alexandria/__init__.py
  matsciml/datasets/alexandria/api.py
  matsciml/datasets/alexandria/dataset.py
  matsciml/datasets/alexandria/devset/data_000.lmdb
  matsciml/datasets/alexandria/devset/data_000.lmdb-lock
  matsciml/datasets/alexandria/tests/__init__.py
  matsciml/datasets/alexandria/tests/test_alexandria.py
  scripts/download_datasets.py
Labels: enhancement, data

#148 Add minimal end-to-end workflow
  .github/workflows/run_pytest_endtoend.yml
  matsciml/tests/test_pipeline.py
Labels: code maintenance

#154 Enable Intel XPU usage and examples
  .github/workflows/run_pytest_endtoend.yml
  .github/workflows/run_pytest_lightning.yml
  examples/devices/xpu_example.py
  matsciml/__init__.py
  matsciml/lightning/__init__.py
  matsciml/lightning/ddp.py
  matsciml/lightning/xpu.py
Labels: enhancement, performance

#157 CI environment fix and validation
  .github/workflows/run_pytest_datasets.yml
  .github/workflows/run_pytest_endtoend.yml
  .github/workflows/run_pytest_lightning.yml
  .github/workflows/run_pytest_models.yml
  .github/workflows/run_pytest_repo.yml
Labels: code maintenance

#156 Upstream MACE implementation
  examples/model_demos/mace_wrapper.py
  matsciml/common/inspection.py
  matsciml/models/pyg/mace/__init__.py
  matsciml/models/pyg/mace/wrapper/__init__.py
  matsciml/models/pyg/mace/wrapper/model.py
  matsciml/models/pyg/mace/wrapper/tests/test_mace_wrapper.py
  pyproject.toml
Labels: enhancement, models, dependencies
