Repository IntelLabs/matsciml, pull requests merged in 2024-01, with the labels that each got.

#86 82 feature request allow user specified reductions for embeddings
  examples/datasets/carolina_db/single_task_devset.py
  matsciml/models/base.py
Labels: ux, training

#93 Fix issue https://github.com/IntelLabs/matsciml/issues/91
  matsciml/datasets/transforms/frame_averaging.py
Labels: bug

#96 Returning Embeddings from M3GNet
  matsciml/models/dgl/m3gnet.py
Labels: enhancement, models

#89 Documentation on how to implement new datasets
  matsciml/datasets/README.md
Labels: documentation

#72 Adding MACE model and equivariant output block
  examples/model_demos/mace/MACE_EF.ipynb
  examples/model_demos/mace/MACE_EF_Train.py
  matsciml/models/base.py
  matsciml/models/common.py
  matsciml/models/pyg/__init__.py
  matsciml/models/pyg/mace/data/__init__.py
  matsciml/models/pyg/mace/data/atomic_data.py
  matsciml/models/pyg/mace/data/neighborhood.py
  matsciml/models/pyg/mace/data/utils.py
  matsciml/models/pyg/mace/modules/__init__.py
  matsciml/models/pyg/mace/modules/blocks.py
  matsciml/models/pyg/mace/modules/irreps_tools.py
  matsciml/models/pyg/mace/modules/models.py
  matsciml/models/pyg/mace/modules/radial.py
  matsciml/models/pyg/mace/modules/symmetric_contraction.py
  matsciml/models/pyg/mace/modules/utils.py
  matsciml/models/pyg/mace/tools/__init__.py
  matsciml/models/pyg/mace/tools/cg.py
  matsciml/models/pyg/mace/tools/checkpoint.py
  matsciml/models/pyg/mace/tools/scatter.py
  matsciml/models/pyg/mace/tools/torch_tools.py
  matsciml/models/pyg/mace/tools/utils.py
Labels: models
