Repository IntelLabs/matsciml, pull requests merged in 2024-04, with the labels that each got.

#168 Materials Project `pymatgen` devset fix
  matsciml/datasets/materials_project/api.py
  matsciml/datasets/materials_project/devset/data.lmdb
  matsciml/datasets/materials_project/devset/data.lmdb-lock
  matsciml/datasets/materials_project/devset/request.json
  pyproject.toml
Labels: bug, dependencies

#170 Compositional split generation routines
  matsciml/preprocessing/README.md
  matsciml/preprocessing/generate_summary.py
  matsciml/preprocessing/produce_split.py
  matsciml/preprocessing/utils.py
Labels: enhancement

#173 Bumping `ruff` to latest 0.3.5
  .pre-commit-config.yaml
  pyproject.toml
Labels: dependencies

#175 Downgrading `torch_geometric` to 2.4.0
  pyproject.toml
Labels: bug, dependencies

#167 Callback for Sharpness Aware Minimization
  examples/callbacks/SAM.py
  matsciml/lightning/callbacks.py
  matsciml/lightning/tests/test_sam.py
Labels: enhancement

#182 SAM force regression task fix
  matsciml/lightning/callbacks.py
  matsciml/lightning/tests/test_sam.py
Labels: bug

#187 SAM Callback DDP and Multi Data Fixes.
  matsciml/lightning/callbacks.py
Labels: bug

#191 Noisy node positions pretraining task
  examples/tasks/pretraining/denoising_nodes.py
  matsciml/datasets/transforms/__init__.py
  matsciml/datasets/transforms/pretraining/__init__.py
  matsciml/datasets/transforms/pretraining/noisy_positions.py
  matsciml/datasets/transforms/pretraining/tests/__init__.py
  matsciml/datasets/transforms/pretraining/tests/test_noisy_positions.py
  matsciml/models/base.py
  matsciml/models/tests/test_tasks.py
Labels: enhancement, training
