Repository IntelLabs/matsciml, pull requests merged in 2024-08, with the labels that each got.

#266 Implementing `MaterialsTrajectoryDataset`
  matsciml/datasets/__init__.py
  matsciml/datasets/materials_project/__init__.py
  matsciml/datasets/materials_project/dataset.py
Labels: enhancement, data

#270 Implementing loss scaling scheduler callback and schedulers
  examples/callbacks/loss_scheduling.py
  matsciml/lightning/callbacks.py
  matsciml/lightning/loss_scaling.py
  matsciml/lightning/tests/test_loss_scaling_schedules.py
Labels: enhancement, training

#271 Noisy node modification
  matsciml/datasets/transforms/pretraining/noisy_positions.py
Labels: training

#272 Allow Loading of Checkpoints in Experiments Pipeline
  experiments/README.md
  experiments/task_config/task_config.py
Labels: ux

#273 Matgl upgrade to 1.1.3 + CHGNet Integration
  experiments/configs/models/chgnet_dgl.yaml
  matsciml/models/dgl/__init__.py
  matsciml/models/dgl/chgnet.py
  matsciml/models/dgl/m3gnet.py
  matsciml/models/dgl/tensornet.py
  matsciml/models/dgl/tests/test_chgnet.py
  pyproject.toml
Labels: models

#278 Initial kickstarting of Sphinx and readthedocs configuration
  .readthedocs.yaml
  README.md
  conda.yml
  docs/.gitignore
  docs/Makefile
  docs/source/best-practices.rst
  docs/source/callbacks.rst
  docs/source/conf.py
  docs/source/datasets.rst
  docs/source/experiment-interface.rst
  docs/source/how-to.rst
  docs/source/index.rst
  docs/source/models.rst
  docs/source/training.rst
  docs/source/transforms.rst
  matsciml/lightning/__init__.py
  pyproject.toml
Labels: documentation

#279 Readme update
  README.md
Labels: documentation

#281 Contributing instructions
  CONTRIBUTING.md
  README.md
  docs/source/developers.rst
  docs/source/index.rst
Labels: documentation
