Repository IntelLabs/matsciml, pull requests merged in 2024-09, with the labels that each got.

#284 SAM callback step/epoch skipping configuration
  matsciml/lightning/callbacks.py
Labels: ux, training

#286 Configuring `sphix` to use class `__init__` docstrings
  docs/source/conf.py
Labels: documentation, code maintenance

#288 SAM configuration check fixes
  examples/callbacks/SAM.py
  matsciml/lightning/callbacks.py
Labels: bug, training

#294 Parity inference task
  docs/source/inference.rst
  matsciml/lightning/data_utils.py
  matsciml/models/inference.py
  matsciml/models/tests/test_parity_inference.py
Labels: enhancement, ux, inference

#295 Docs: Experiment CLI Common Params
  docs/source/experiment-interface.rst
Labels: documentation

#296 Fixes to parity inference task
  docs/source/index.rst
  docs/source/inference.rst
  matsciml/lightning/data_utils.py
  matsciml/models/inference.py
Labels: bug, documentation, ux, inference

#298 Training documentation update
  docs/source/best-practices.rst
  docs/source/inference.rst
  docs/source/training.rst
Labels: documentation
