Repository IntelLabs/matsciml, pull requests merged in 2024-10, with the labels that each got.

#301 LMDB traversal cli
  docs/source/best-practices.rst
  docs/source/datasets.rst
  matsciml/datasets/lmdb_cli.py
  pyproject.toml
Labels: documentation, ux, data

#303 Quantile-based loss mechanism
  docs/source/training.rst
  matsciml/models/losses.py
  matsciml/models/tests/test_losses.py
Labels: training

#305 `pymatgen` structure creation patch
  matsciml/datasets/transforms/pbc.py
  matsciml/datasets/utils.py
Labels: bug, data

#306 Relaxed `pyproject.toml` specifications and improved dependency resolution
  README.md
  conda.yml
  matsciml/common/packages.py
  pyproject.toml
Labels: ux, code maintenance

#308 Adding `BatchQuantileLoss` to `__all__`
  matsciml/models/losses.py
Labels: bug

#310 ASE Backend For PBC Computation
  matsciml/datasets/tests/test_transforms.py
  matsciml/datasets/transforms/pbc.py
  matsciml/datasets/utils.py
Labels: enhancement

#312 Revising optional package imports
  matsciml/__init__.py
  matsciml/common/packages.py
  matsciml/lightning/__init__.py
  matsciml/lightning/xpu.py
  matsciml/models/pyg/__init__.py
Labels: bug, dependencies
