Repository IntelLabs/matsciml, pull requests merged in 2024-07, with the labels that each got.

#237 Quality of life and helper callback functions
  examples/callbacks/autocorrelation.py
  examples/callbacks/helper.py
  matsciml/datasets/utils.py
  matsciml/lightning/callbacks.py
  matsciml/lightning/tests/test_helper.py
  matsciml/models/base.py
Labels: ux, training

#248 Default MACE atomic energies
  matsciml/models/pyg/mace/wrapper/model.py
Labels: enhancement, ux, models

#251 Updating Some Pytests
  matsciml/models/base.py
  matsciml/models/dgl/tests/test_m3gnet.py
  matsciml/models/dgl/tests/test_tensornet.py
  matsciml/models/pyg/mace/wrapper/tests/test_mace_wrapper.py
  matsciml/models/pyg/tests/test_egnn.py
  matsciml/models/pyg/tests/test_faenet.py
Labels: code maintenance

#255 Updating `ManualGradientClip` hook
  matsciml/lightning/callbacks.py
Labels: bug

#256 Atom weighted loss functions and `loss_func` argument refactor
  matsciml/models/base.py
  matsciml/models/losses.py
  matsciml/models/tests/test_losses.py
  matsciml/models/tests/test_task_loss_scaling.py
Labels: enhancement, training

#257 Implementing exponential moving average Lightning callback
  examples/callbacks/exponential_moving_average.py
  matsciml/lightning/callbacks.py
  matsciml/lightning/tests/test_ema.py
  matsciml/models/base.py
  matsciml/modules/exponential_moving_average.py
Labels: enhancement, training

#259 Fixing checkpoint mechanism for exponential moving average
  matsciml/models/base.py
Labels: bug, training
