Repository IntelLabs/matsciml, pull requests merged in 2024-05, with the labels that each got.

#204 Node embedding projections for `ForceRegressionTask`
  matsciml/models/base.py
  matsciml/models/tests/test_tasks.py
Labels: training

#195 Materials Project Devset Update
  matsciml/datasets/materials_project/cli.py
  matsciml/datasets/materials_project/devset/data.lmdb
  matsciml/datasets/materials_project/devset/data.lmdb-lock
  matsciml/datasets/materials_project/devset/request.json
  matsciml/datasets/tests/test_collate_function.py
  matsciml/datasets/tests/test_multi_dataset.py
  matsciml/lightning/tests/test_multi_module.py
Labels: data

#213 Prettifying PyTest output in Github actions
  .github/workflows/run_pytest_datasets.yml
  .github/workflows/run_pytest_endtoend.yml
  .github/workflows/run_pytest_lightning.yml
  .github/workflows/run_pytest_models.yml
  .github/workflows/run_pytest_repo.yml
  pyproject.toml
Labels: dependencies, code maintenance

#215 ASE `Calculator` interface
  .github/workflows/run_pytest_interfaces.yml
  examples/interfaces/ase_from_pretrained.py
  examples/interfaces/ase_from_scratch.py
  matsciml/common/relaxation/ase_utils.py
  matsciml/common/relaxation/ml_relaxation.py
  matsciml/common/relaxation/optimizers/__init__.py
  matsciml/common/relaxation/optimizers/lbfgs_torch.py
  matsciml/interfaces/__init__.py
  matsciml/interfaces/ase/__init__.py
  matsciml/interfaces/ase/base.py
  matsciml/interfaces/ase/tests/test_ase_calc.py
  matsciml/models/base.py
Labels: enhancement, inference

#224 Multitask ASE interface
  examples/interfaces/ase_multitask_from_pretrained.py
  matsciml/interfaces/ase/base.py
  matsciml/interfaces/ase/multitask.py
  matsciml/interfaces/ase/tests/test_multi_task.py
  matsciml/models/base.py
Labels: enhancement, inference

#228 Rename src/dst Nodes For Point Cloud Featurization
  matsciml/datasets/alexandria/dataset.py
  matsciml/datasets/alexandria/tests/test_alexandria.py
  matsciml/datasets/base.py
  matsciml/datasets/carolina_db/dataset.py
  matsciml/datasets/colabfit/dataset.py
  matsciml/datasets/colabfit/tests/test_dataset.py
  matsciml/datasets/lips/dataset.py
  matsciml/datasets/lips/tests/test_lips_reps.py
  matsciml/datasets/materials_project/dataset.py
  matsciml/datasets/materials_project/tests/test_mp_reps.py
  matsciml/datasets/nomad/dataset.py
  matsciml/datasets/ocp_datasets.py
  matsciml/datasets/oqmd/dataset.py
  matsciml/datasets/symmetry/dataset.py
Labels: bug, data
